"""MigracionBase

Revision ID: a7ce73d74e18
Revises: fa2e0a0c2454
Create Date: 2021-07-02 18:01:21.208901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ce73d74e18'
down_revision = 'fa2e0a0c2454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Publicaciones', 'UUID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Publicaciones', sa.Column('UUID', sa.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
